name: CI
on: [push, pull_request]
jobs:
  tests:
    services:
      mysql:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: restapi
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.x', '14.x']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Node.js (v${{ matrix.node-version }}.x)
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version
        name: Check Node.js version
      - run: npm install
      - run: cp .env.testing .env
      - run: npm run test


